**被删除元素一定要在列表中，否则会报错**

```python
data = ['1', '2', '3']

print(data.remove(2))
```

```bash
Traceback (most recent call last):
  File "/home/adam/Documents/Code/python/2.py", line 3, in <module>
    print(data.remove(2))
ValueError: list.remove(x): x not in list
```

----------------

```python
data = ['1', '2', '3']

print(data.remove('2'))
print(data)
```

```bash
None
['1', '3']
```